{"name": "test_login_succeed", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <case.test_login.test_login_one.TestLogin object at 0x00000188AA01D448>\n\n    @pytest.mark.testmark\n    def test_login_succeed(self):\n        res = Login(username=TestLogin().test_get_csv_data()[1][0], password=TestLogin().test_get_csv_data()[1][1]).login()\n>       assert TestLogin().test_get_csv_data()[1][2] == res[\"code\"]\nE       AssertionError: assert '1' == 1\n\ntest_login_one.py:36: AssertionError"}, "attachments": [{"name": "stdout", "source": "19d81278-e3a7-4838-9991-d335f13c8778-attachment.txt", "type": "text/plain"}], "start": 1633701125861, "stop": 1633701125886, "uuid": "6b170218-c4b5-4d0a-8b24-84d56dd34aa1", "historyId": "8acc0a1cf70cf2dbe369f345a62355e2", "testCaseId": "0a7f8b3b5ac1e4c2c2d0b7a5ab437480", "fullName": "case.test_login.test_login_one.TestLogin#test_login_succeed", "labels": [{"name": "tag", "value": "testmark"}, {"name": "parentSuite", "value": "case.test_login"}, {"name": "suite", "value": "test_login_one"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-JBQBBC5"}, {"name": "thread", "value": "9268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_login.test_login_one"}]}